name: Build, Test, and Deploy

on:
  push:
    branches: "**"
    tags-ignore: ["**"]
  pull_request:
  release:
    types: [ "released" ]

jobs:
  call-build:
    uses: "KyoriPowered/.github/.github/workflows/shared-ci.yaml@trunk"
    with:
      runtime_version: 17
      publish_releases: true
      gradle_release_publish_tasks: "publishPlugins"
    permissions:
      actions: "write"
      contents: "write"
      id-token: "write"
    secrets: "inherit"
